import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { Banner } from "../components/Banner";
import LeftPanel from "../components/LeftPanel";
import { Navbar } from "../components/Navbar";
import { TweetForm } from "../components/TweetForm";
import RightPanel from "../components/RightPanel";
import { TweetList } from "../components/TweetList";

const Home: NextPage = () => {
  const { data } = useSession();

  return (
    <>
      <Head>
        <title>Chief Twit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center text-white">
        <LeftPanel />

        <main className="flex w-6/12 flex-col items-center border-l-2 border-r-2 border-gray-700 bg-gray-900 ">
          <Navbar />
          <TweetForm />
          <TweetList />
        </main>

        <RightPanel />
      </div>
      {!data ? <Banner /> : null}
    </>
  );
};

export default Home;
